# Generated by Django 3.2.5 on 2021-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_subjects_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='classs',
        ),
        migrations.AddField(
            model_name='subjects',
            name='classes',
            field=models.ManyToManyField(blank=True, to='account.Classes'),
        ),
    ]
