# Generated by Django 3.2.5 on 2021-08-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_students_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='profile_pic',
            field=models.URLField(blank=True, default='avatar.png'),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.URLField(blank=True, default='avatar.png'),
        ),
    ]
