# Generated by Django 3.2.5 on 2021-08-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210808_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='profile_pic',
            field=models.URLField(blank=True),
        ),
    ]
