# Generated by Django 3.2.5 on 2021-08-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_results_sequences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='student',
        ),
        migrations.AddField(
            model_name='students',
            name='results',
            field=models.ManyToManyField(blank=True, to='account.Results'),
        ),
    ]
