# Generated by Django 3.2.5 on 2021-08-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_results_classs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequences',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='students',
            name='results',
        ),
        migrations.AddField(
            model_name='results',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.academic_years'),
        ),
        migrations.AddField(
            model_name='results',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.students'),
        ),
    ]
