# Generated by Django 3.2.5 on 2021-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolinfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email1', models.EmailField(blank=True, max_length=254)),
                ('Email2', models.EmailField(blank=True, max_length=254)),
                ('Number1', models.CharField(blank=True, max_length=15)),
                ('Number2', models.CharField(blank=True, max_length=15)),
                ('Number3', models.CharField(blank=True, max_length=15)),
                ('Pobox', models.CharField(blank=True, max_length=15)),
                ('Location1', models.CharField(blank=True, max_length=15)),
                ('Location2', models.CharField(blank=True, max_length=15)),
                ('Location3', models.CharField(blank=True, max_length=15)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitemessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student_applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_names', models.CharField(max_length=100)),
                ('Parent_Contact', models.CharField(max_length=100)),
                ('Alternative_contact', models.CharField(blank=True, max_length=100)),
                ('Parent_Email', models.EmailField(max_length=254)),
                ('Alternative_email', models.EmailField(blank=True, max_length=254)),
                ('Town_of_Residence', models.CharField(blank=True, max_length=15)),
                ('Date_of_birth', models.DateField(blank=True)),
                ('Previous_school', models.CharField(max_length=100)),
                ('Birth_certificate', models.FileField(upload_to='media/Student_applications')),
                ('Clinic_card', models.FileField(upload_to='media/Student_applications')),
                ('Approved', models.BooleanField(default=False)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
