# Generated by Django 3.2.5 on 2021-09-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210909_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class1_applications',
            name='parent_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='class2_6_applications',
            name='parent_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form1_applications',
            name='parent_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form2_4_applications',
            name='parent_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lowersixth_applications',
            name='parent_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nursery_applications',
            name='parent_name',
            field=models.CharField(max_length=100),
        ),
    ]
