# Generated by Django 3.2.5 on 2021-09-09 08:25

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210909_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class1_applications',
            name='Birth_certificate',
            field=models.FileField(upload_to='media/Student_applications/cl1', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='class1_applications',
            name='Clinical_card_showing_vaccination_taken',
            field=models.FileField(upload_to='media/Student_applications/cl1', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='class1_applications',
            name='Nursery_school_certificate',
            field=models.FileField(upload_to='media/Student_applications/cl1', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='class2_6_applications',
            name='Birth_certificate',
            field=models.FileField(upload_to='media/Student_applications/cl2_6', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='class2_6_applications',
            name='Previous_class_report_card',
            field=models.FileField(upload_to='media/Student_applications/cl2_6', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='form1_applications',
            name='Acceptance_slip',
            field=models.FileField(upload_to='media/Student_applications/f1', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='form1_applications',
            name='Birth_certificate',
            field=models.FileField(upload_to='media/Student_applications/f1', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='form1_applications',
            name='Class6_report_card',
            field=models.FileField(upload_to='media/Student_applications/f1', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='form2_4_applications',
            name='Birth_certificate',
            field=models.FileField(upload_to='media/Student_applications/f2_4', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='form2_4_applications',
            name='Previous_class_report_card',
            field=models.FileField(upload_to='media/Student_applications/f2_4', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='lowersixth_applications',
            name='Birth_certificate',
            field=models.FileField(upload_to='media/Student_applications/l6', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='lowersixth_applications',
            name='Form5_report_card',
            field=models.FileField(upload_to='media/Student_applications/l6', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='lowersixth_applications',
            name='GCE_results_slip_or_printed_page_of_results',
            field=models.FileField(upload_to='media/Student_applications/l6', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='nursery_applications',
            name='Birth_certificate',
            field=models.FileField(upload_to='media/Student_applications/nur', validators=[blog.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='nursery_applications',
            name='Clinical_card_showing_vaccination_taken',
            field=models.FileField(upload_to='media/Student_applications/nur', validators=[blog.validators.validate_file_size]),
        ),
    ]
