# Generated by Django 3.2.5 on 2021-09-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210909_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='class1_applications',
            name='Physical_condition',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='class1_applications',
            name='Sex',
            field=models.CharField(choices=[('M', 'United States'), ('F', 'France')], default='M', max_length=100),
        ),
        migrations.AddField(
            model_name='class2_6_applications',
            name='Physical_condition',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='class2_6_applications',
            name='Sex',
            field=models.CharField(choices=[('M', 'United States'), ('F', 'France')], default='M', max_length=100),
        ),
        migrations.AddField(
            model_name='form1_applications',
            name='Physical_condition',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='form1_applications',
            name='Sex',
            field=models.CharField(choices=[('M', 'United States'), ('F', 'France')], default='M', max_length=100),
        ),
        migrations.AddField(
            model_name='form2_4_applications',
            name='Physical_condition',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='form2_4_applications',
            name='Sex',
            field=models.CharField(choices=[('M', 'United States'), ('F', 'France')], default='M', max_length=100),
        ),
        migrations.AddField(
            model_name='lowersixth_applications',
            name='Physical_condition',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='lowersixth_applications',
            name='Sex',
            field=models.CharField(choices=[('M', 'United States'), ('F', 'France')], default='M', max_length=100),
        ),
        migrations.AddField(
            model_name='nursery_applications',
            name='Physical_condition',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='nursery_applications',
            name='Sex',
            field=models.CharField(choices=[('M', 'United States'), ('F', 'France')], default='M', max_length=100),
        ),
    ]
