# Generated by Django 3.2.5 on 2021-09-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210909_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='class1_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('LS', ' LowerSixth'), ('F4', 'Form4'), ('F3', 'Form3'), ('F2', 'Form2'), ('F1', 'Form1'), ('C6', 'Class6'), ('C5', 'Class5'), ('C4', 'Class4'), ('C3', 'Class3'), ('C2', 'Class2'), ('C1', 'Class1'), ('PN', 'Pre-nursery'), ('N1', 'Nursery1')], default='C1', max_length=10),
        ),
        migrations.AddField(
            model_name='class2_6_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('LS', ' LowerSixth'), ('F4', 'Form4'), ('F3', 'Form3'), ('F2', 'Form2'), ('F1', 'Form1'), ('C6', 'Class6'), ('C5', 'Class5'), ('C4', 'Class4'), ('C3', 'Class3'), ('C2', 'Class2'), ('C1', 'Class1'), ('PN', 'Pre-nursery'), ('N1', 'Nursery1')], default='C2', max_length=10),
        ),
        migrations.AddField(
            model_name='form1_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('LS', ' LowerSixth'), ('F4', 'Form4'), ('F3', 'Form3'), ('F2', 'Form2'), ('F1', 'Form1'), ('C6', 'Class6'), ('C5', 'Class5'), ('C4', 'Class4'), ('C3', 'Class3'), ('C2', 'Class2'), ('C1', 'Class1'), ('PN', 'Pre-nursery'), ('N1', 'Nursery1')], default='F1', max_length=10),
        ),
        migrations.AddField(
            model_name='form2_4_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('LS', ' LowerSixth'), ('F4', 'Form4'), ('F3', 'Form3'), ('F2', 'Form2'), ('F1', 'Form1'), ('C6', 'Class6'), ('C5', 'Class5'), ('C4', 'Class4'), ('C3', 'Class3'), ('C2', 'Class2'), ('C1', 'Class1'), ('PN', 'Pre-nursery'), ('N1', 'Nursery1')], default='F2', max_length=10),
        ),
        migrations.AddField(
            model_name='lowersixth_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('LS', ' LowerSixth'), ('F4', 'Form4'), ('F3', 'Form3'), ('F2', 'Form2'), ('F1', 'Form1'), ('C6', 'Class6'), ('C5', 'Class5'), ('C4', 'Class4'), ('C3', 'Class3'), ('C2', 'Class2'), ('C1', 'Class1'), ('PN', 'Pre-nursery'), ('N1', 'Nursery1')], default='LS', max_length=10),
        ),
        migrations.AddField(
            model_name='nursery_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('LS', ' LowerSixth'), ('F4', 'Form4'), ('F3', 'Form3'), ('F2', 'Form2'), ('F1', 'Form1'), ('C6', 'Class6'), ('C5', 'Class5'), ('C4', 'Class4'), ('C3', 'Class3'), ('C2', 'Class2'), ('C1', 'Class1'), ('PN', 'Pre-nursery'), ('N1', 'Nursery1')], default='PN', max_length=10),
        ),
    ]
