# Generated by Django 3.2.5 on 2021-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_lowersixth_applications_admission_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class1_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('C1', 'Class1')], default='C1', max_length=10),
        ),
        migrations.AlterField(
            model_name='class2_6_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('C6', 'Class6'), ('C5', 'Class5'), ('C4', 'Class4'), ('C3', 'Class3'), ('C2', 'Class2')], default='C2', max_length=10),
        ),
        migrations.AlterField(
            model_name='form1_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('F1', 'Form1')], default='F1', max_length=10),
        ),
        migrations.AlterField(
            model_name='form2_4_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('F4A', 'Form4 Arts'), ('F4S', 'Form4 Science'), ('F3', 'Form3'), ('F2', 'Form2')], default='F2', max_length=10),
        ),
        migrations.AlterField(
            model_name='lowersixth_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('LSA', ' Lower Sixth Arts'), ('LSS', ' Lower Sixth Science')], default='LSA', max_length=10),
        ),
        migrations.AlterField(
            model_name='nursery_applications',
            name='Admission_Class',
            field=models.CharField(blank=True, choices=[('PN', 'Pre-nursery'), ('N1', 'Nursery1')], default='PN', max_length=10),
        ),
    ]
