# Generated by Django 3.2.5 on 2021-09-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210909_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery_applications',
            name='Previous_school',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
