# Generated by Django 3.2.5 on 2021-09-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_nursery_applications_previous_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class1_applications',
            old_name='Sex',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='class2_6_applications',
            old_name='Sex',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='form1_applications',
            old_name='Sex',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='form2_4_applications',
            old_name='Sex',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='lowersixth_applications',
            old_name='Sex',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='nursery_applications',
            old_name='Sex',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='teacher_applications',
            old_name='Sex',
            new_name='Gender',
        ),
    ]
